version: '3.9'

services:
  rabbitmq:
    container_name: 'rabbitmq'
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
  
  elasticsearch:
    container_name: 'elasticsearch'
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.6.2'
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      discovery.type: 'single-node'